---

- name: Roller节点服务器基本状态巡检.

  hosts: roller
  remote_user: root
  gather_facts: yes
  vars:
  tasks:
    - name: 巡检开始
      shell: |
        echo "==========["{{ ansible_hostname }} - {{ ansible_ssh_host }}" - 巡 检 开 始 - "{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"]=========="
  
    - name: 系统基本指标巡检
      shell: |
        echo "系统运行时间"
        uptime
        echo

        echo "内存状态检查"
        free -m
        echo

        echo "整体状态检查"
        vmstat 3 5
        echo

        echo "磁盘空间使用率"
        df -h
        echo

        echo "网络状态检查"
        netstat -i
        echo

    - name: 巡检结束
      shell: |
        echo "==========["{{ ansible_hostname }} - {{ ansible_ssh_host }}" - 巡 检 结 束 - "{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"]=========="

