---

- name: NFS节点服务器基本状态巡检.

  hosts: nfs
  remote_user: root
  gather_facts: yes
  vars:
  tasks:
    - name: 巡检开始
      shell: |
        echo "==========["{{ ansible_hostname }} - {{ ansible_ssh_host }}" - 巡 检 开 始 - "{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"]=========="

    - name: nfs服务检查
      shell: |
        echo "nfs服务检查"
        systemctl status nfs
        echo

    - name: 巡检结束
      shell: |
        echo "==========["{{ ansible_hostname }} - {{ ansible_ssh_host }}" - 巡 检 结 束 - "{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"]=========="

