---
# 变更用户密码

- name: 变更用户密码.
  hosts: all
  gather_facts: false
  tasks:
    - name: change passwordd for user
      user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        update_password: always
      with_items: "{{ ops_chpass_user }}"
