---
# 

- name: 运维巡检-操作系统基础巡检.
  hosts: all
  gather_facts: true
  serial: 1
  tasks:
    - name: 操作系统基础巡检开始
      shell: |
        echo "==========["{{ ansible_hostname }} - {{ ansible_ssh_host }}" - 巡 检 开 始 - "{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"]=========="

    # 运行状态
    - name: 操作系统基础-运行时间和负载
      shell: |
        echo "# 1.操作系统基础-运行时间和负载"
        uptime
        echo

    # CPU
    - name: 操作系统基础-CPU-负载和使用情况
      shell: |
        echo "# 2.操作系统基础-CPU-负载和使用情况"
        vmstat 3 5
        echo

    - name: 操作系统基础-CPU-型号和核心数
      shell: |
        echo "# 3.操作系统基础-CPU-型号和核心数"
        cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c
        echo

    - name:  操作系统基础-CPU-TOP10
      shell: |
        echo "# 4.操作系统基础-CPU-TOP10"
        ps -aux | sort -k3nr | head -10
        echo

    # 内存
    - name: 操作系统基础-内存-使用率
      shell: |
        echo "# 5.操作系统基础-内存-使用率"
        free -h
        echo

    - name: 操作系统基础-内存-TOP10
      shell: |
        echo "# 6.操作系统基础-内存-TOP10"
        ps -aux | sort -k4nr | head -10
        echo

    # 磁盘
    - name: 操作系统基础-磁盘-容量使用情况
      shell: |
        echo "# 7.操作系统基础-磁盘-容量使用情况"
        df -h
        echo

    - name: 操作系统基础-磁盘-inodes使用情况
      shell: |
        echo "# 8.操作系统基础-磁盘-inodes使用情况"
        df -i
        echo

    # 网络
    - name: 操作系统基础-网络-接口信息
      shell: |
        echo "# 9.操作系统基础-网络-接口信息"
        ip address
        echo

    - name: 操作系统基础-网络-端口监听信息
      shell: |
        echo "# 10.操作系统基础-网络-端口监听信息"
        ss -ntlup
        echo

    - name: 巡检结束
      shell: |
        echo "==========["{{ ansible_hostname }} - {{ ansible_ssh_host }}" - 巡 检 结 束 - "{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"]=========="
