- name: use fetch copy 
  hosts: "{{ host }}"
  gather_facts: false
  tasks: 
  - name: fetch copy
    fetch:
      src: "/tmp/{{ host }}_36c221be-6ab2-ef53-1589-fe16877914f4_chk.xml"
      dest: /opt/script/ansible/files
